spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

shipment-service:
  url: ${SHIPMENT_SERVICE_URL:http://shipment-service:8081}

fleet-service:
  url: ${FLEET_SERVICE_URL:http://fleet-service:8082}
